# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='songs',
            field=models.ManyToManyField(blank=True, to='musicapp.Song'),
        ),
    ]
